language: python

python:
  - "2.7"
  - "3.4"
  - "pypy"
  - "pypy3"

install:
  - travis_retry pip install -r requirements.txt --allow-external argparse
  - travis_retry pip install coveralls
  - travis_retry pip install coverage
  
script:
  - PYTHONPATH=. coverage run -m unittest discover iutest.tests.iutests -v

after_success:
  - coveralls

matrix:
  fast_finish: true