language: python

python:
  - "2.7"
  - "3.7"

install:
  - travis_retry pip install -r requirements-${TRAVIS_PYTHON_VERSION}.txt
  - travis_retry pip install coveralls
  - travis_retry pip install coverage
  
script:
  - PYTHONPATH=. coverage run -m unittest discover iutest.tests.iutests -v

after_success:
  - coveralls

matrix:
  fast_finish: true