# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f ci_requirements-${{ matrix.python-version }}.txt ]; then pip install -r ci_requirements-${{ matrix.python-version }}.txt; fi
    - name: Test with pytest
      run: |
        pytest iutest/tests/iutests
        
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.3
      with:
        projectBaseDir: ./iutest
        
    - name: TestCoverage
      uses: codecov/codecov-action@v1.0.13
